services:
  spider:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fishsense_data_processing_spider
    volumes:
      - fishsense_data_reef:/mnt/fishsense_data_reef:ro

volumes:
  fishsense_data_reef:
   external: true