[scraper]
interval = "1h"
data_paths = "/e4efs/config/data_paths.json"

[summary]
interval = "2m"

[label_studio]
host = 'labeler.e4e.ucsd.edu'
interval = "1h"

[web_api]
key_store = '/e4efs/data/keys.db'
